name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Test
    timeout-minutes: 15
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint
