name: dispatch github release deploy-notifier

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
    secrets:
      PAT:
        required: true

jobs:
  dispatch:
    name: dispatch
    runs-on: ubuntu-latest

    steps:
      - name: Slack Notify
        run: |
          title=${{ inputs.service }}
          repository=${{ github.repository }}
          tag=${{ github.ref_name }}

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/wafflestudio/snutt-internal/dispatches \
            -d "{\"event_type\": \"trigger-workflow\", \"client_payload\": {\"title\": \"$title\", \"repository\": \"$repository\", \"tag\": \"$tag\"}}"
