name: cron

on:
  schedule:
    - cron: "44 3 * * *" # 수, 토 한국시간 오전 10시

jobs:
  cron:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.0
        with:
          node-version: ${{ matrix.node-version }}

      # cron job을 실행합니다.
      - name: run script
        run: |
          cd apps/kanban-check-script
          yarn install
          NOTION_KANBAN_DATABASE_ID=${{ secrets.NOTION_KANBAN_DATABASE_ID }} \
          NOTION_KANBANBOT_TOKEN=${{ secrets.NOTION_KANBANBOT_TOKEN }} \
          SLACK_TTUNS_TOKEN=${{ secrets.SLACK_TTUNS_TOKEN }} \
          SLACK_CHANNEL=${{ secrets.SLACK_CHANNEL }} \
            yarn send
