name: send-kanban-weekly-summary

on:
  schedule:
    - cron: "20 1 * * 3" # 수요일 한국시간 오전 11시 20분
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"

      # cron job을 실행합니다.
      - name: run script
        run: |
          cd apps/kanban-reporter
          yarn install
          NOTION_KANBAN_DATABASE_ID=${{ secrets.NOTION_KANBAN_DATABASE_ID_2 }} \
          NOTION_EPIC_DATABASE_ID=${{ secrets.NOTION_EPIC_DATABASE_ID_2 }} \
          NOTION_KANBANBOT_TOKEN=${{ secrets.NOTION_KANBANBOT_TOKEN_3 }} \
          SLACK_TTUNS_TOKEN=${{ secrets.SLACK_TTUNS_TOKEN }} \
          SLACK_CHANNEL=${{ secrets.SLACK_CHANNEL }} \
            yarn send:weekly-summary
